# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files

a = Analysis(
    ['server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('keywords.txt', '.'),
        ('frontend/dist', 'frontend/dist'),
        ('.env', '.'),
        *collect_data_files('fpdf'),   # fpdf2 font metrics and internal data
    ],
    hiddenimports=[
        'flask',
        'flask_cors',
        'uuid',
        'idd_generator',
        'fpdf',
        'fpdf.fpdf',
        'fpdf.output',
        'fpdf.fonts',
        'fpdf.drawing',
        'fpdf.enums',
        'fpdf.errors',
        'fpdf.util',
        'fpdf.deprecation',
        'fpdf.image_datastructures',
        'fpdf.image_parsing',
        'fpdf.transitions',
        'fpdf.outline',
        'fpdf.svg',
        'fpdf.table',
        'defusedxml',
        'PIL',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='IPFinder',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)